/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Objective

import com.squareup.moshi.Json

/**
 * 
 *
 * @param objectives 
 */


data class GetObjectives200Response (

    @Json(name = "objectives")
    val objectives: kotlin.collections.List<Objective>? = null

)

