/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Patient

import com.squareup.moshi.Json

/**
 * 
 *
 * @param patients 
 */


data class GetPatients200Response (

    @Json(name = "patients")
    val patients: kotlin.collections.List<Patient>? = null

)

