/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param objectiveId 
 * @param startTime 
 * @param endTime 
 */


data class Metric (

    @Json(name = "objectiveId")
    val objectiveId: java.math.BigDecimal? = null,

    @Json(name = "startTime")
    val startTime: java.time.OffsetDateTime? = null,

    @Json(name = "endTime")
    val endTime: java.time.OffsetDateTime? = null

)

