/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param objectiveId 
 * @param patientId 
 * @param description 
 * @param type 
 */


data class Objective (

    @Json(name = "objectiveId")
    val objectiveId: java.math.BigDecimal,

    @Json(name = "patientId")
    val patientId: java.math.BigDecimal,

    @Json(name = "description")
    val description: kotlin.String,

    @Json(name = "type")
    val type: Objective.Type

) {

    /**
     * 
     *
     * Values: counter,duration,latency
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "Counter") counter("Counter"),
        @Json(name = "Duration") duration("Duration"),
        @Json(name = "Latency") latency("Latency");
    }
}

