/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param userId 
 * @param username 
 * @param firstName 
 * @param surname 
 */


data class User (

    @Json(name = "userId")
    val userId: java.math.BigDecimal,

    @Json(name = "username")
    val username: kotlin.String,

    @Json(name = "firstName")
    val firstName: kotlin.String? = null,

    @Json(name = "surname")
    val surname: kotlin.String? = null

)

